name: Daily Create Tag

on:
  schedule:
    - cron: "*/5 *  * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      #   - name: Generate release tag
      #     id: generate_release_tag
      #     uses: amitsingh-007/next-release-tag@v6.0.0
      #     with:
      #       github_token: ${{ secrets.GITHUB_TOKEN }}
      #       tag_prefix: "nightly-"
      #       tag_template: "yyyy.mm.dd.i"
      - name: Create tag if necessary
        id: daily-version
        uses: fregante/daily-version-action@v2
        with:
          prefix: nightly-

    #   - name: Create Release
    #     if: steps.daily-version.outputs.created
    #     uses: softprops/action-gh-release@v2
    #     with:
    #       name: Release ${{ steps.daily-version.outputs.version }}
    #       tag_name: ${{ steps.daily-version.outputs.version }}
    #       token: ${{secrets.GITHUB_TOKEN}}
    #       generate_release_notes: true
    #       prerelease: true
