name: Daily Create Tag

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Create tag if necessary
        id: daily-version
        uses: fregante/daily-version-action@v2
        with:
          prefix: nightly-
      - name: Created?
        if: steps.daily-version.outputs.created
        run: echo "Created ${{ steps.daily-version.outputs.version }}"
