# name: Weekly Team Sync
# on: [push]
# # on:
# #   schedule:
# #     - cron: 5 * * * *

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout branch
#         uses: actions/checkout@v4

#       - name: Generate release tag
#         id: generate_release_tag
#         uses: amitsingh-007/next-release-tag@v6.0.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           tag_prefix: "v"
#           tag_template: "yyyy.mm.dd.i"

#       - name: Create Release
#         uses: softprops/action-gh-release@v2
#         with:
#           name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
#           tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
#           token: ${{secrets.GITHUB_TOKEN}}
#           generate_release_notes: true

name: Nightly Snapshot

# on:
#   schedule:
#     - cron: "51 * * * *"
on: [push]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout branch "master"
        uses: actions/checkout@v2
        with:
          ref: "main"
      - name: Release snapshot
        id: release-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
