# name: Weekly Team Sync
# on: [push]
# # on:
# #   schedule:
# #     - cron: 5 * * * *

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout branch
#         uses: actions/checkout@v4

#       - name: Generate release tag
#         id: generate_release_tag
#         uses: amitsingh-007/next-release-tag@v6.0.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           tag_prefix: "v"
#           tag_template: "yyyy.mm.dd.i"

#       - name: Create Release
#         uses: softprops/action-gh-release@v2
#         with:
#           name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
#           tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
#           token: ${{secrets.GITHUB_TOKEN}}
#           generate_release_notes: true

name: Nightly Snapshot

# on:
#   schedule:
#     - cron: "51 * * * *"
on: [push]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set Dist Version
        run: |
          BUILD_NUMBER="${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
          echo "${BUILD_NUMBER}"
          VERSION="$(mvn -q -U -Dexpression=project.build.finalName help:evaluate -DforceStdout=true -DbuildNumber=${BUILD_NUMBER})"
          echo "DIST_VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Create Tag
        uses: actions/github-script@v6
        with:
          script: |
            const {DIST_VERSION} = process.env          
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${DIST_VERSION}`,
                sha: context.sha
            })
