# name: Weekly Team Sync
# on: [push]
# # on:
# #   schedule:
# #     - cron: 5 * * * *

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout branch
#         uses: actions/checkout@v4

#       - name: Generate release tag
#         id: generate_release_tag
#         uses: amitsingh-007/next-release-tag@v6.0.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           tag_prefix: "v"
#           tag_template: "yyyy.mm.dd.i"

#       - name: Create Release
#         uses: softprops/action-gh-release@v2
#         with:
#           name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
#           tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
#           token: ${{secrets.GITHUB_TOKEN}}
#           generate_release_notes: true

name: Nightly Snapshot

# on:
#   schedule:
#     - cron: "51 * * * *"
on: [push]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "latest"
          tag_exists_error: false
          message: "Latest release"

      # Print result using the env variable.
      - run: |
          echo "Tag already present: ${{ env.TAG_EXISTS }}"

      # Print result using the action output.
      - run: |
          echo "Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"
